# Generated by Django 5.2.2 on 2025-06-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('male', models.BooleanField()),
                ('age', models.PositiveIntegerField()),
                ('education', models.PositiveSmallIntegerField()),
                ('currentSmoker', models.BooleanField()),
                ('cigsPerDay', models.PositiveSmallIntegerField()),
                ('BPMeds', models.BooleanField()),
                ('prevalentStroke', models.BooleanField()),
                ('prevalentHyp', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('totChol', models.FloatField()),
                ('sysBP', models.FloatField()),
                ('diaBP', models.FloatField()),
                ('BMI', models.FloatField()),
                ('heartRate', models.PositiveSmallIntegerField()),
                ('glucose', models.FloatField()),
                ('TenYearCHD', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
