# Generated by Django 5.2.2 on 2025-06-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientuser_is_active_patientuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='TenYearCHD',
        ),
    ]
