# Generated by Django 5.2.2 on 2025-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_tenyearchd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cigsPerDay',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
