# Generated by Django 5.2.2 on 2025-06-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_height_patient_triglycerides_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
